import ArrowOrange from './ArrowTellow.svg'
import Oval from './Oval.svg'
import ArrowWhite from './footer.svg'
import Logo from './logo.svg'
import OneCard from './1.svg'
import TwoCard from './2.svg'
import ThreeCard from './3.svg'
import FourCard from './4.svg'
import SixCard from './6.svg'
import Bed from './Bed.svg'
import Shower from './Shower.svg'
import Size from './Size.svg'
import House from './Garage.svg'
import Down from './down.svg'
import People from './dfdf.svg'
import PeopleR from './DFF.svg'
import ProfileAva from './profile.svg'
export { ProfileAva, ArrowOrange, Oval, House, ArrowWhite, Logo, OneCard, TwoCard, ThreeCard, FourCard, SixCard, Bed, Shower, Size, Down, People, PeopleR }